// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0kmT3NitHTFQqE2wKNyuVkWtaAuaAeSE',
    appId: '1:228825407854:web:6dd903c64e62d5db05217f',
    messagingSenderId: '228825407854',
    projectId: 'multi-store-flutter-ea50d',
    authDomain: 'multi-store-flutter-ea50d.firebaseapp.com',
    storageBucket: 'multi-store-flutter-ea50d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC30jJoKz5ogdz4dJFodKVD_JiRsqfTJn4',
    appId: '1:228825407854:android:2c96dfb413fb99f005217f',
    messagingSenderId: '228825407854',
    projectId: 'multi-store-flutter-ea50d',
    storageBucket: 'multi-store-flutter-ea50d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjYBijX-VQSajrUlsqr1H4aM_k1k2vErU',
    appId: '1:228825407854:ios:d55c657fb4da3f7805217f',
    messagingSenderId: '228825407854',
    projectId: 'multi-store-flutter-ea50d',
    storageBucket: 'multi-store-flutter-ea50d.appspot.com',
    iosClientId: '228825407854-gc62nk496n3cgq0lmdelm5o1s2dg9e3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiStoreUdemy',
  );
}
